OOP school library: set up associations
bhushan354/OOP-School-Library pull request #3
Opened 2023-11-09 11:17 UTC by bhushan354

In this PR I have implemented following things : 

- Set up associations between classes and objects.
- Created a class Classroom .
- Created the has-many/belongs-to relationship between Classroom and Student.

Thank You ,
Bhushan .

2023-11-09 12:13 UTC, skyv26 requested changes
## Hi @bhushan354, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjVhZjBiZjUzZmYxZjI1NGFhNGQ0ZjIyN2FhOTcwNDZlZmUzNmZkMiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/L422JoNlBBBD42zkQ9/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 

## Required Changes ♻️

- [ ] Please 🙏🏻 adhere to the project `requirements` because as I noticed that while reviewing your **code**, you missed the `Rental` class as per the milestone. You should add the `Rental` class as instructed in the task, which you can find below:

![image](https://github.com/bhushan354/OOP-School-Library/assets/66476329/f2345fff-4806-49ca-96f9-0537c1c830c4)
 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 12:13 UTC, skyv26 commented on classroom.rb
> +    students << student
- [ ] Good job so far, but it seems like you made a small mistake which can cause an error while running the code because you are adding `student` into the `students` array, which is a local variable for the `add_student` functions which means that once you added the new student data, once the scope of the function ends, your array memory will vanish. So to avoid the situation, put the `@` symbol before the `students` because `@students` is an instance variable which will hold your data even after the end of the scope of the `add_student`.

**Note: Yes, data inside the `@students` array will be empty once the program is closed.**

2023-11-09 12:13 UTC, skyv26 commented on person.rb
> +  attr_reader :rentals
- [ ] Kindly make sure that while establishing the `association` between the two classes, you make sure that the `rentals` should have both the `getter` and `setter`, you did very well by adding the `rentals` as read-only, but when you add the person with rentals in upcoming milestones, you will face an issue, because to set the value or `add` the rentals into the list, you should make the `rentals` instance variable both `read` and `write`. So first thing you need to do is put your `:rentals` at the end of `attr_accessor` alongside `name` and `age` and second things is you need to provide the window for adding the `rentals` method like `add_rental` where inside you will push the coming `rental` into the `@rentals` array.

![image](https://github.com/bhushan354/OOP-School-Library/assets/66476329/8fbe91cc-1cdb-4792-8d60-84a6f017b559)

2023-11-09 12:13 UTC, skyv26 commented on classroom.rb
> +end
- [ ] Kindly remove the `student` class from here, as per instructions, your class or `module` should be in a separate files, I think you already have the `student` class, so that is why you don't need to add the class here again.

2023-11-09 12:13 UTC, skyv26 commented on book.rb
> +  end
- [ ] Kindly do the same here as I mentioned in my above comment, make sure that you don't have any redundancy in your code.

2023-11-09 16:14 UTC, bhushan354 commented
@skyv26 sir I've added rental class in book.rb file

2023-11-09 16:34 UTC, skyv26 commented
@bhushan354 as I mentioned put everything in separate file

2023-11-10 01:46 UTC, bhushan354 commented
@skyv26 Oh ! I get it now , thanks for your review !, I will make the changes as per your review .

2023-11-10 02:00 UTC, bhushan354 commented on person.rb
> +  attr_reader :rentals
I have resolved this issue , Thanks for your feedback :smile:

2023-11-10 02:00 UTC, bhushan354 commented on classroom.rb
> +    students << student
I have resolved this issue , Thanks for your feedback :smile:

2023-11-10 02:01 UTC, bhushan354 commented on classroom.rb
> +end
I have resolved this issue , Thanks for your feedback :smile:

2023-11-10 02:07 UTC, bhushan354 commented on book.rb
> +  end
I have resolved this issue , Thanks for your feedback :smile:

2023-11-10 02:30 UTC, Shedrack-Sunday approved these changes
Hi @bhushan354         👍 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Ruby features  ✔️
- [x] Kudus on fixing all changes suggested by the last reviewer   
- [x] Kudus on meeting the requirements   👏 


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-10 14:17 UTC, merged